data_handler:
  class: Alpha158
  module_path: aiq.dataset.handler
  kwargs:
    processors:
      - class: Dropna
        module_path: aiq.dataset.processor
        kwargs:
          fields_group: 'label'
      - class: DropExtremeLabel
        module_path: aiq.dataset.processor
        kwargs:
          fields_group: 'label'
          percentile: 0.975
      - class: CSZScoreNorm
        module_path: aiq.dataset.processor
        kwargs:
          fields_group: 'label'
dataset:
  class: Dataset
  module_path: aiq.dataset.dataset
  kwargs:
    instruments: "csi300"
    segments:
      train: ['2008-01-01', '2020-03-31']
      valid: ['2020-04-01', '2020-06-30']
      test: ['2020-07-01', '2023-12-31']
model:
  class: DEnsembleModel
  module_path: aiq.models.double_ensemble
  kwargs:
    base_model: 'gbm'
    loss: 'mse'
    num_models: 6
    enable_sr: True
    enable_fs: True
    alpha1: 1
    alpha2: 1
    bins_sr: 10
    bins_fs: 5
    decay: 0.5
    sample_ratios: [0.8, 0.7, 0.6, 0.5, 0.4]
    sub_weights: [1, 1, 1, 1, 1, 1]
    num_boost_round: 200
    early_stopping_rounds: 50
    colsample_bytree: 0.8879
    learning_rate: 0.1
    subsample: 0.8789
    max_depth: 8
    num_leaves: 32
    num_threads: 4
    metric: 'rmse'
    verbosity: -1
