data_handler:
  class: Alpha158
  module_path: aiq.dataset.handler
  kwargs:
    processors:
      - class: Dropna
        module_path: aiq.dataset.processor
        kwargs:
          fields_group: "label"
      - class: CSZScoreNorm
        module_path: aiq.dataset.processor
        kwargs:
          fields_group: "label"
dataset:
  class: Dataset
  module_path: aiq.dataset.dataset
  kwargs:
    instruments: "000300.SH"
    segments:
      train: ["2008-01-01", "2020-03-31"]
      valid: ["2020-04-01", "2020-06-30"]
      test: ["2020-07-01", "2023-12-31"]
model:
  class: LGBModel
  module_path: aiq.models.lightgbm
  kwargs:
    model_params:
      objective: "mse"
      learning_rate: 0.1
      colsample_bytree: 0.8879
      max_depth: 8
      num_leaves: 210
      subsample: 0.8789
      lambda_l1: 205.6999
      lambda_l2: 580.9768
      metric: "rmse"
      nthread: 4
