market: "csi300"
data_handler:
  class: Alpha158
  module_path: aiq.dataset.handler
  kwargs:
    processors:
      - class: Dropna
        module_path: aiq.dataset.processor
        kwargs:
          target_cols: ['LABEL']
      - class: CSZScoreNorm
        module_path: aiq.dataset.processor
        kwargs:
          target_cols: ['LABEL']
dataset:
  class: Dataset
  module_path: aiq.dataset.dataset
  segments:
    train: ['2008-07-01', '2024-12-31']
    valid: ['2022-01-01', '2024-12-31']
    test: ['2023-01-01', '2024-05-01']
model:
  name: 'LGB'
  params: {
    'objective': 'mse',
    'learning_rate': 0.1,
    'colsample_bytree': 0.8879,
    'max_depth': 8,
    'num_leaves': 210,
    'subsample': 0.8789,
    'lambda_l1': 205.6999,
    'lambda_l2': 580.9768,
    'metric': 'rmse',
    'nthread': 4
  }
