data_handler:
  class: Alpha158
  module_path: aiq.dataset.handler
  kwargs:
    instruments: "000300.SH"
    start_time: "2016-01-01"
    end_time: "2023-12-31"
    fit_start_time: "2017-01-01"
    fit_end_time: "2022-06-30"
    processors:
      - class: Dropna
        module_path: aiq.dataset.processor
        kwargs:
          fields_group: "label"
      - class: CSZScoreNorm
        module_path: aiq.dataset.processor
        kwargs:
          fields_group: "label"
dataset:
  class: Dataset
  module_path: aiq.dataset.dataset
  kwargs:
    segments:
      train: ["2017-01-01", "2022-06-30"]
      valid: ["2022-07-01", "2022-12-31"]
      test: ["2023-01-01", "2023-06-30"]
    label_names: ["RETN_5D"]
model:
  class: LGBModel
  module_path: aiq.models.lightgbm
  kwargs:
    objective: "mse"
    learning_rate: 0.1
    colsample_bytree: 0.8879
    max_depth: 8
    num_leaves: 210
    subsample: 0.8789
    lambda_l1: 205.6999
    lambda_l2: 580.9768
    metric: "rmse"
    nthread: 4
