dataset:
  start_time: '2008-01-01'
  end_time: '2023-05-01'
  segments: {
    'train': [ '2008-07-01', '2021-12-31' ],
    'valid': [ '2022-01-01', '2022-11-31' ],
    'test': [ '2023-01-01', '2023-05-01' ]
  }
  feature_names: ['Adj_Open', 'Adj_Close', 'Adj_High', 'Adj_Low', 'Volume']
  label_names: ['Return']

model:
  name: 'NLinear'
  params: {
    'features': 'MS',
    'seq_len': 96,
    'pred_len': 1,
    'enc_in': 7,
    'individual': 0,
    'pct_start': 0.3,
    'train_epochs': 10,
    'batch_size': 1,
    'learning_rate': 0.01,
  }
