market: &market 000905.SH
data_handler:
  class: MarketAlpha158
  module_path: aiq.dataset.handler
  kwargs:
    instruments: *market
    start_time: "2016-01-01"
    end_time: "2023-12-31"
    fit_start_time: "2017-01-01"
    fit_end_time: "2022-06-20"
    market_names: ["000903.SH", "000300.SH", "000905.SH"]
    processors:
      - class: CSWinsorize
        module_path: aiq.dataset.processor
        kwargs:
          fields_group: "feature"
          exclude_cols: ["IND_CLS"]
      - class: CSNeutralize
        module_path: aiq.dataset.processor
        kwargs:
          industry_col: "IND_CLS"
          cap_col: "FUND_CAP"
          factor_cols:
            ["FUND_BP", "FUND_EP", "^CS_TURN_(?:MEAN|STD)_(?:5|10|20|30|60)D$"]
      - class: Dropna
        module_path: aiq.dataset.processor
        kwargs:
          fields_group: "label"
    market_processors:
      - class: RobustZScoreNorm
        module_path: aiq.dataset.processor
        kwargs:
          fields_group: "feature"
          clip_outlier: true
      - class: Fillna
        module_path: aiq.dataset.processor
        kwargs:
          fields_group: "feature"
dataset:
  class: TSDataset
  module_path: aiq.dataset.dataset
  kwargs:
    universe: *market
    segments:
      train: ["2017-01-01", "2022-06-20"]
      valid: ["2022-07-01", "2022-12-20"]
      test: ["2023-01-01", "2023-06-30"]
    seq_len: 16
    label_names: ["RETN_5D"]
    use_augmentation: false
model:
  class: PPNetModel
  module_path: aiq.models.ppnet
  kwargs:
    d_feat: 140
    d_market: 63
    d_emb: 16
    d_model: 256
    t_nhead: 4
    s_nhead: 2
    dropout: 0.5
    beta: 3.0
    epochs: 100
    batch_size: 1
    learning_rate: 0.001
    criterion_name: "IC"
    early_stopping_patience: 10
