market: &market 000905.SH
data_handler:
  class: MarketAlpha158
  module_path: aiq.dataset.handler
  kwargs:
    instruments: *market
    start_time: "2013-01-01"
    end_time: "2023-12-31"
    fit_start_time: "2014-01-01"
    fit_end_time: "2022-06-20"
    market_names: ["000903.SH", "000300.SH", "000905.SH"]
    processors:
      - class: CSWinsorize
        module_path: aiq.dataset.processor
        kwargs:
          fields_group: "feature"
          exclude_cols: ["MKT_CLS", "IND_CLS_L1", "IND_CLS_L2"]
      - class: CSNeutralize
        module_path: aiq.dataset.processor
        kwargs:
          industry_col: "IND_CLS_L1"
          cap_col: "MKT_CAP"
          factor_cols: ["BP", "EP", "^TURN_(?:MEAN|STD)_(?:5|10|20|30|60)D$"]
      - class: Dropna
        module_path: aiq.dataset.processor
        kwargs:
          fields_group: "label"
    market_processors:
      - class: RobustZScoreNorm
        module_path: aiq.dataset.processor
        kwargs:
          fields_group: "feature"
          clip_outlier: true
      - class: Fillna
        module_path: aiq.dataset.processor
        kwargs:
          fields_group: "feature"
dataset:
  class: TSDataset
  module_path: aiq.dataset.dataset
  kwargs:
    universe: *market
    segments:
      train: ["2014-01-01", "2022-06-20"]
      valid: ["2022-07-01", "2022-12-20"]
      test: ["2023-01-01", "2023-06-30"]
    seq_len: 16
    label_names: ["RETN_5D"]
    norm_feature_start_index: 6
    norm_feature_end_index: 143
    use_augmentation: false
model:
  class: PPNetModel
  module_path: aiq.models.ppnet
  kwargs:
    pv_feature_start_index: 6
    pv_feature_end_index: 143
    market_feature_start_index: 143
    market_feature_end_index: 206
    industry_feature_index: 1
    industry_embedding_dim: 8
    seq_len: 16
    pred_len: 1
    d_feat: 137
    d_model: 256
    t_nhead: 4
    s_nhead: 2
    dropout: 0.5
    beta: 3.0
    epochs: 30
    batch_size: 1
    learning_rate: 0.0001
    criterion_name: "MSE"
