data_handler:
  class: MarketAlpha158
  module_path: aiq.dataset.handler
  kwargs:
    instruments: "000906.SH"
    start_time: "2016-01-01"
    end_time: "2023-06-30"
    fit_start_time: "2017-01-01"
    fit_end_time: "2022-06-30"
    processors:
      - class: CSNeutralize
        module_path: aiq.dataset.processor
        kwargs:
          industry_col: "IND_CLS_L1_CAT"
          cap_col: "MKT_CAP"
          factor_cols:
            [
              "KMID",
              "KLEN",
              "KMID2",
              "KUP",
              "KUP2",
              "KLOW",
              "KLOW2",
              "KSFT",
              "KSFT2",
              "KOC",
              "^(?:ROC|MA|STD|MAX|MIN|QTLU|QTLD|CORR|CORD|VMA|VSTD|WVMA|RSV|IMAX|IMIN|IMXD|SUMP|VSUMP)(?:5|10|20|30|60)D$",
              "^TURN_(?:MEAN|STD)_(?:5|10|20|30|60)D$",
              "RETN_5D",
            ]
      - class: RobustZScoreNorm
        module_path: aiq.dataset.processor
        kwargs:
          fields_group: "feature"
          clip_outlier: true
      - class: Fillna
        module_path: aiq.dataset.processor
        kwargs:
          fields_group: "feature"
      - class: Dropna
        module_path: aiq.dataset.processor
        kwargs:
          fields_group: "label"
    market_processors:
      - class: RobustZScoreNorm
        module_path: aiq.dataset.processor
        kwargs:
          fields_group: "feature"
          clip_outlier: true
      - class: Fillna
        module_path: aiq.dataset.processor
        kwargs:
          fields_group: "feature"
dataset:
  class: TSDataset
  module_path: aiq.dataset.dataset
  kwargs:
    segments:
      train: ["2017-01-01", "2022-06-30"]
      valid: ["2022-07-01", "2022-12-31"]
      test: ["2023-01-01", "2023-06-30"]
    seq_len: 16
    label_names: ["RETN_5D"]
model:
  class: PPNetModel
  module_path: aiq.models.ppnet
  kwargs:
    d_feat: 138
    d_model: 256
    t_nhead: 4
    s_nhead: 2
    seq_len: 16
    pred_len: 1
    dropout: 0.5
    gate_input_start_index: 144
    gate_input_end_index: 207
    epochs: 30
    batch_size: 1
    learning_rate: 0.0001
    criterion_name: "MSE"
